### ISSUE TITLE
Add dependencies for nodejs - arm64

### ISSUE THREAD

**Issue by SavageFRVR** [Software-Noob/pterodactyl-images#11]
`libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`

Please add the above dependencies for the Node.js Arm64 docker images. They are required for canvas an npm package.

**Comment by Software-Noob** [comment]
I don't personally use canvas and don't see the need for these niche packages to increase the image size for 99.99% of users. Instead, I recommend you fork and customize the image to your liking should you run browsers in Pterodactyl containers.
