### ISSUE TITLE
How to add?

### ISSUE THREAD

**Issue by Mirt90** [Software-Noob/pterodactyl-images#2]
I need help for add Java 16

**Comment by Software-Noob** [comment]
You can see the image URLs in the readme.

Open your egg on the admin panel, select the nest -> your egg, and add the URL to your docker image section. You can also change the docker image in the startup tab for each server.

**Comment by Mirt90** [comment]
> You can see the image URLs in the readme.
> 
> Open your egg on the admin panel, select the nest -> your egg, and add the URL to your docker image section. You can also change the docker image in the startup tab for each server.

Thank you very much for your time and your work! You helped me a lot.

**Comment by Software-Noob** [comment]
> > You can see the image URLs in the readme.
> > 
> > Open your egg on the admin panel, select the nest -> your egg, and add the URL to your docker image section. You can also change the docker image in the startup tab for each server.
> 
> Thank you very much for your time and your work! You helped me a lot.

Happy to hear that!
