### ISSUE TITLE
epoll_wait broken with new docker root image

### ISSUE THREAD

**Issue by Maescool** [Software-Noob/pterodactyl-images#21]
0d87ea5823af80be5bbd995e85f9b844d9c8d939 broke epoll_wait so we get this error on mc servers:
` [Netty Epoll Server IO #12/WARN]: Unexpected exception in the selector loop.
io.netty.channel.unix.Errors$NativeIoException: epoll_wait(..) failed: Function not implemented`

**Comment by Software-Noob** [comment]
What's the Minecraft version and exact Docker image? This sounds like an outdated netty package problem, which has been updated in newer distros and MC releases.

**Comment by Maescool** [comment]
it's on mc 1.19 (there is a fix for this on 1.19.1, with netty update to 4.1.77, that one checks for availability of that function)
ghcr.io/software-noob/pterodactyl-images:java_17 is the docker image, updated today and started to get those errors

**Comment by Software-Noob** [comment]
> it's on mc 1.19 (there is a fix for this on 1.19.1, with netty update to 4.1.77, that one checks for availability of that function) ghcr.io/software-noob/pterodactyl-images:java_17 is the docker image, updated today and started to get those errors

Yeah, I found that out. New images are building and should fix this issue for older versions until proper support is implemented.
