### ISSUE TITLE
Sourcemod egg is hardcoded for csgo

### ISSUE THREAD

**Issue by justinnobledev** [Software-Noob/pterodactyl-images#29]
Could we have it so that the egg either detects what game it is running and installs it to the proper location or have an extra environment variable where we can set the game folder.

**Comment by Software-Noob** [comment]
I only have experience and a use case for the CS:GO, which is what it was built for. What other games there require specific locations?

**Comment by justinnobledev** [comment]
TF2 for example uses the tf folder and CSS uses cstrike. Outside of those two games I don't have that much experience but I believe most source games tend to support sourcemod and most if not all use a different base game folder name. I tend to also use this image when setting up new servers as to slightly automate some of the tedium of doing so.

**Comment by Software-Noob** [comment]
I can make the path a configurable option later today

**Comment by Software-Noob** [comment]
It can be modified with the egg environment variable `INSTALL_PATH` now. When not set, it will default to csgo.

I'd prefer to automate it based on the currently installed game at some point.  Would need to find time to install each game and verify the base folder (tf,dod,css,csgo,etc).
