### ISSUE TITLE
Sourcemod outdated version

### ISSUE THREAD

**Issue by Prefix** [Software-Noob/pterodactyl-images#32]
Please update SM to latest stable version 1.11
https://github.com/Software-Noob/pterodactyl-images/blob/main/games/source-sourcemod/entrypoint.sh#L48

**Comment by Software-Noob** [comment]
It has been updated and is in the function https://github.com/Software-Noob/pterodactyl-images/blob/main/games/source-sourcemod/entrypoint.sh#L67-L70

Those variables are not used anymore. I will remove them later.

**Comment by Software-Noob** [comment]
Removed in https://github.com/Software-Noob/pterodactyl-images/commit/e8512838e8e0a68b125b4d26aa81f671820e73cb and should no versions be provided, the URL validation will fail and it will default to the latest
