### ISSUE TITLE
GraalVM JDK 17 AArch64/ARM64

### ISSUE THREAD

**Issue by joelra** [Software-Noob/pterodactyl-images#35]
Is it possible to build AArch64 (AMR64) version of JDK 17 of GraalVM? I'm having a hard time following their documentation here, but it seems to indicate that this should work on AArch64: https://www.eclipse.org/openj9/docs/openj9_support/#openjdk-17.

Am I missing something in reading this? Forgive me since I'm ignorant on the process of how to even go about creating a dockerfile to support a given platform.

**Comment by Software-Noob** [comment]
GraalVM 17 image already exists and is multiarch. You can see it in [both the files](https://github.com/Software-Noob/pterodactyl-images/tree/main/java-graalvm) and [readme](https://github.com/Software-Noob/pterodactyl-images#supported-platforms).
