### ISSUE TITLE
[Bug Report]: java_8_graalvm appears to be broken

### ISSUE THREAD

**Issue by Micim987** [Software-Noob/pterodactyl-images#47]
### Bug Report

When testing GraalVM as an option in Pterodactyl Panel Java 17 works perfectly fine but Java 8 is throwing this error when starting 

```
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from software-noob/pterodactyl-images 
Status: Image is up to date for ghcr.io/software-noob/pterodactyl-images:java_8_graalvm 
Digest: sha256:65dce2f53519500e9c33747b871b7067f9854a55b7c4316aeb6669028425d198 
[Pterodactyl Daemon]: Finished pulling Docker container image
exec /bin/bash: exec format error
```

Pterodactyl and wings are both in their vanilla state running on an ARM64 system if any additional details are needed I'll be happy to provide them

Edit: I should add that our startup command looks like this `java -Xms$(({{SERVER_MEMORY}}*{{RAM_PERCENT}}/100))M -Xmx$(({{SERVER_MEMORY}}*{{RAM_PERCENT}}/100))M {{JVM_ARGS}} -jar {{SERVER_JARFILE}}` and Eclipse Java 8 works fine in the same configuration. Also I am bad at markdown

**Comment by Software-Noob** [comment]
The error indicates that the image is not built for your cpu architecture. It should support both amd64 and arm64 as they are all built in the same workflow.

I can test a bit later

**Comment by Software-Noob** [comment]
GraalVM 8 specifically only appears to ship the x86_64 binary that I missed. Added a note to the readme regarding this. Unfortunately, it's not supported upstream - unless they push it as part of a security fix since Java 8 is no longer actively supported.
