### ISSUE TITLE
[Image Request]: Java 20 Images

### ISSUE THREAD

**Issue by TH3N3WN00B** [Software-Noob/pterodactyl-images#48]
### Does this apply to existing image

No

### What's the image for (e.g. NodeJS, Dotnet, Shenandoah, etc)

pterodactyl (?)

### Image Request

Petition to add Azul Java 20 to the images

couldnt find it on the docker [webstie](https://hub.docker.com/r/azul/zulu-openjdk) but it is aviable in azul [website](https://www.azul.com/downloads/?package=jdk#download-openjdk)

also prepare for GraalVM java 20 CE, dev builds aviable [here](https://github.com/graalvm/graalvm-ce-dev-builds/releases)

**Comment by Software-Noob** [comment]
Azul Java has been added. GraalVM will be added whenever they publish a docker image upstream, as I won't be maintaining a custom image for each new commit.
