### ISSUE TITLE
[Image Request]: liberica-openjdk

### ISSUE THREAD

**Issue by rafalohaki** [Software-Noob/pterodactyl-images#57]
### Does this apply to existing image

No

### What's the image for (e.g. NodeJS, Dotnet, Shenandoah, etc)

java

### Image Request

bellsoft/liberica-openjdk-debian
at least 8, 11, 16 and 17

**Comment by Software-Noob** [comment]
Implemented in https://github.com/Software-Noob/pterodactyl-images/commit/ce51a6f7ebbf99d8812c297b128a36a8d1bdf01e
