### ISSUE TITLE
[Image Request]: Preparation for JDK 21

### ISSUE THREAD

**Issue by TH3N3WN00B** [Software-Noob/pterodactyl-images#63]
### Does this apply to existing image

Yes

### What's the image for (e.g. NodeJS, Dotnet, Shenandoah, etc)

Java

### Image Request

Java 21 was made public today, will update this Issue with more links as more distributions make it available:

For now, [Oracle](https://www.oracle.com/java/technologies/downloads/)

Edit 1: Azul Zulu has been released [here](https://www.azul.com/downloads/?version=java-21-lts&package=jdk#zulu)

Edit 2: [GraalVM](https://www.graalvm.org/downloads/#) has also been released

Edit 3: [Amazon Corretto](https://docs.aws.amazon.com/corretto/latest/corretto-21-ug/downloads-list.html) joins the chat

Edit 4: After a long battle against bureaucracy [Temurin](https://github.com/adoptium/temurin21-binaries/releases/tag/jdk-21%2B35) has released is first Linux only builds (full release is expected to hit around Oct [17th](https://adoptium.net/blog/2023/09/temurin21-delay/))

**Comment by WarnDa** [comment]
Hello,
When do java 21 images will be released ?

**Comment by NoltoxGit** [comment]
> Hello, When do java 21 images will be released ?

J'ai ouvert une issue pour ça si tu veux : #66
