### ISSUE TITLE
[EGG / Image Request] BombSquad Server

### ISSUE THREAD

**Issue by DeathGOD7** [Software-Noob/pterodactyl-images#7]
Link to game : https://www.froemling.net/apps/bombsquad

Server downloads : https://files.ballistica.net/bombsquad/builds/

Server install docs : https://www.froemling.net/docs/hosting-bombsquad-games

Docker File: https://github.com/alibo/bombsquad-docker/blob/master/Dockerfile (not made for pterodactyl)

Game Server is in python and said to be working with 3.8.
As your python ARM64 image is working fine but it doesn't seem to run the game server.

Looking at code there was: ``apt-get install -y python3.8 libpython3.8 locales libsdl2-2.0-0`` in that docker file linked above (not made for pterodactyl). And some people said that libpython and libsdl2 are needed to run the server.

**Comment by Software-Noob** [comment]
That's a generic Python application. There's no reason for a game-specific image in this case.

**Comment by DeathGOD7** [comment]
> That's a generic Python application. There's no reason for a game-specific image in this case.

Well as I have posted above, the generic one doesn't have libpython and libsdl in its install script. And it's necessary for running the server. (As said by most people.)
